// GENERATED by .design-sync/gen-roster.mjs — do not edit by hand.
// Bundle entry for the design-sync converter: the exact RFDS surface,
// re-exported so every component lands on window.RFDS.

// MUST stay first: ES modules evaluate imports in source order, so this
// installs a browser-safe `process` before any component module reads
// server env at module scope. See .design-sync/process-shim.ts.
import "./process-shim";

export { ErrorBoundary } from "../src/components/error-boundary";
export { BecomeContributor } from "../src/components/home/become-contributor";
export { ByTheNumbers } from "../src/components/home/by-the-numbers";
export { EcosystemLibraries } from "../src/components/home/ecosystem-libraries";
export { ExecutiveMessage } from "../src/components/home/executive-message";
export { FeaturedCollections } from "../src/components/home/featured-collections";
export { FeaturedLook } from "../src/components/home/featured-look";
export { FoundationHero } from "../src/components/home/foundation-hero";
export { FoundingMembers } from "../src/components/home/founding-members";
export { HeroBadges } from "../src/components/home/hero-badges";
export { Hero } from "../src/components/home/hero";
export { JoinMovementCTA } from "../src/components/home/join-movement-cta";
export { LimitedDrops } from "../src/components/home/limited-drops";
export { MissionStatement } from "../src/components/home/mission-statement";
export { PastDropsCollections } from "../src/components/home/past-drops-collections";
export { PastDrops } from "../src/components/home/past-drops";
export { ThreePillars } from "../src/components/home/three-pillars";
export { Footer } from "../src/components/layout/footer";
export { Header } from "../src/components/layout/header";
export { MobileMenu } from "../src/components/layout/mobile-menu";
export { TableOfContents } from "../src/components/rfds/TableOfContents";
export { AccordionContent } from "../src/components/rfds/accordion";
export { FormInput } from "../src/components/rfds/form-input";
export { SearchInput } from "../src/components/rfds/search-input";
export { ContributorCard, ContributorIcon, SemanticAlert, SemanticAvatar, SemanticBadge, SemanticButton, SemanticCard, SemanticInput, SemanticSeparator } from "../src/components/rfds/semantic-components";
export { StatCard } from "../src/components/rfds/stat-card";
export { Table } from "../src/components/rfds/table";
export { Timeline, TimelineItem, TimelineProgress, TimelineStep } from "../src/components/rfds/timeline";
export { RISLibraryRankings } from "../src/components/ris/ris-library-rankings";
export { RISScoreBreakdown } from "../src/components/ris/ris-score-breakdown";
export { Button, ButtonLink } from "../src/components/ui/button";
export { Checkbox } from "../src/components/ui/checkbox";
export { Collapsible } from "../src/components/ui/collapsible";
export { Dialog } from "../src/components/ui/dialog";
export { Input } from "../src/components/ui/input";
export { Label } from "../src/components/ui/label";
export { LibraryCard } from "../src/components/ui/library-card";
export { Pill } from "../src/components/ui/pill";
export { ProductCard } from "../src/components/ui/product-card";
export { ProductGallery } from "../src/components/ui/product-gallery";
export { Radio } from "../src/components/ui/radio";
export { Rating } from "../src/components/ui/rating";
export { ScrollReveal } from "../src/components/ui/scroll-reveal";
export { SegmentedControl } from "../src/components/ui/segmented-control";
export { Select } from "../src/components/ui/select";
export { Separator } from "../src/components/ui/separator";
export { Switch } from "../src/components/ui/switch";
export { Textarea } from "../src/components/ui/textarea";
export { ThemeToggle as ThemeSegmentedControl } from "../src/components/ui/theme-toggle";
export { Tooltip } from "../src/components/ui/tooltip";
export { UserAvatar } from "../src/components/ui/user-avatar";
export { SignInButton } from "../src/features/auth/sign-in-button";
export { ImpactSection } from "../src/features/impact/impact-section";
export { MaintainerProgress } from "../src/features/maintainer-progress/maintainer-progress";
export { UsernameInput } from "../src/features/maintainer-progress/username-input";
