// One-time extraction of the Geist / Geist Mono webfonts into a durable,
// committed font kit for the design-system bundle.
//
// Why: the app loads fonts with next/font/google, which downloads the woff2
// into .next/ at build time and defines --font-geist-sans / --font-geist-mono
// on the html element from a Next-generated stylesheet. None of that exists
// in the design-system bundle: the compiled CSS references
// `font-family: var(--font-geist-sans)` but nothing ever defines it and no
// @font-face ships, so every rendered design silently falls back to Arial.
// Neither the render check nor a screenshot diff can catch that — both sides
// fall back identically — so it has to be fixed deliberately here.
//
// .next/ is a build artifact and won't exist on a fresh clone, hence: run this
// once, commit .design-sync/fonts/ + fonts.css, and build-css.mjs folds the
// stylesheet into the bundle CSS on every build. Re-run only to refresh the
// font files (needs a prior `next build`).
import { existsSync, mkdirSync, readFileSync, readdirSync, copyFileSync, writeFileSync, statSync } from 'node:fs';
import { resolve, basename } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const CHUNKS = resolve(ROOT, '.next/static/chunks');
const MEDIA = resolve(ROOT, '.next/static/media');
const FONTS_OUT = resolve(ROOT, '.design-sync/fonts');
const CSS_OUT = resolve(ROOT, '.design-sync/fonts.css');

// Families we ship, and the CSS variable each one has to satisfy.
const FAMILIES = { Geist: '--font-geist-sans', 'Geist Mono': '--font-geist-mono' };

if (!existsSync(CHUNKS)) {
  console.error(`[FONTS] ${CHUNKS} missing — run \`npm run build\` first, then re-run this script.`);
  process.exit(1);
}

const css = readdirSync(CHUNKS)
  .filter((f) => f.endsWith('.css'))
  .map((f) => readFileSync(resolve(CHUNKS, f), 'utf8'))
  .join('\n');

const rules = [...css.matchAll(/@font-face\{([^}]*)\}/g)].map((m) => m[1]);
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

mkdirSync(FONTS_OUT, { recursive: true });
const out = [];
const counters = {};
let copied = 0;

for (const body of rules) {
  const family = /font-family:\s*([^;]+)/.exec(body)?.[1]?.trim().replace(/^['"]|['"]$/g, '');
  if (!family || !(family in FAMILIES)) continue; // skips "Geist Fallback" (local(Arial), no file)
  const url = /url\(([^)]+)\)/.exec(body)?.[1]?.replace(/^['"]|['"]$/g, '');
  if (!url) continue;
  const src = resolve(MEDIA, basename(url));
  if (!existsSync(src)) { console.error(`  ! missing ${basename(url)} — skipped`); continue; }

  const n = (counters[family] = (counters[family] ?? 0) + 1);
  const name = `${slug(family)}-${n}.woff2`;
  copyFileSync(src, resolve(FONTS_OUT, name));
  copied++;

  // Rebuild the rule against the copied file, preserving unicode-range so
  // browsers still only fetch the subsets a page actually needs.
  const keep = body
    .split(';')
    .map((d) => d.trim())
    .filter((d) => d && !/^src:/.test(d) && !/^font-family:/.test(d));
  out.push(
    `@font-face {\n  font-family: "${family}";\n  ${keep.join(';\n  ')};\n` +
      `  src: url("./fonts/${name}") format("woff2");\n}`,
  );
}

if (!copied) {
  console.error('[FONTS] no Geist @font-face rules found — did the build change fonts?');
  process.exit(1);
}

// The variables the compiled Tailwind CSS actually reads. Next sets these on
// <html>; nothing does in the bundle, so define them at :root here.
const vars = Object.entries(FAMILIES)
  .map(([family, v]) => `  ${v}: "${family}", ${family.includes('Mono')
    ? 'ui-monospace, SFMono-Regular, Menlo, monospace'
    : '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'};`)
  .join('\n');

writeFileSync(
  CSS_OUT,
  [
    '/* GENERATED by .design-sync/extract-fonts.mjs — committed on purpose.',
    '   Geist / Geist Mono, lifted out of the next/font build output so the',
    '   design-system bundle ships real brand fonts instead of falling back.',
    '   Folded into the bundle CSS by .design-sync/build-css.mjs. */',
    '',
    ...out,
    '',
    ':root {',
    vars,
    '}',
    '',
  ].join('\n'),
);

const kb = readdirSync(FONTS_OUT).reduce((n, f) => n + statSync(resolve(FONTS_OUT, f)).size, 0) / 1024;
console.error(`fonts: ${copied} woff2 (${kb.toFixed(0)} KB) → .design-sync/fonts/`);
console.error(`       ${out.length} @font-face rule(s) + ${Object.keys(FAMILIES).length} vars → .design-sync/fonts.css`);
