// Generates cfg.componentSrcMap for the RFDS barrel.
// There is no dist/.d.ts tree in this repo (RFDS is a barrel inside a Next.js
// app), so the converter cannot discover the roster on its own. We resolve
// every RFDS re-export back to its declaring source file with ts-morph and
// emit an explicit componentSrcMap — the documented inclusion knob.
import { Project, Node } from 'ts-morph';
import { writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const project = new Project({ tsConfigFilePath: resolve(ROOT, 'tsconfig.json') });

// The barrels that collectively export the whole RFDS surface.
const BARRELS = [
  'src/components/rfds/primitives.ts',
  'src/components/rfds/components.ts',
  'src/components/rfds/layouts.ts',
  'src/components/rfds/semantic-components.tsx',
  'src/components/rfds/timeline.tsx',
  'src/components/rfds/TableOfContents.tsx',
  'src/components/rfds/table.tsx',
  'src/components/rfds/stat-card.tsx',
  'src/components/rfds/form-input.tsx',
  'src/components/rfds/search-input.tsx',
  'src/components/rfds/accordion.tsx',
];

const map = {};
const skipped = [];

for (const rel of BARRELS) {
  const sf = project.getSourceFile(resolve(ROOT, rel));
  if (!sf) { console.error(`! missing barrel: ${rel}`); continue; }
  for (const [name, decls] of sf.getExportedDeclarations()) {
    if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) continue;
    // Value declarations only — drop type-only exports (TableColumn, etc.).
    const valueDecl = decls.find(
      (d) => Node.isVariableDeclaration(d) || Node.isFunctionDeclaration(d) || Node.isClassDeclaration(d),
    );
    if (!valueDecl) { skipped.push(`${name} (type-only)`); continue; }
    const file = relative(ROOT, valueDecl.getSourceFile().getFilePath());
    // The barrel may rename on re-export (primitives.ts does
    // `export { ThemeToggle as ThemeSegmentedControl }`). The declaring file
    // only knows the local name, so the entry has to re-alias or the RFDS
    // name never lands on window.RFDS.
    const local = valueDecl.getName?.() ?? name;
    if (map[name] && map[name].file !== file) console.error(`! ${name}: ${map[name].file} vs ${file} — keeping first`);
    else map[name] = { file, local };
  }
}

// The RFDS "Layers" exports are namespace objects, not components.
const NOT_COMPONENTS = new Set(['Primitives', 'Components', 'Layouts']);
for (const n of NOT_COMPONENTS) delete map[n];

// roster.json stays {Name: srcPath} — that is the cfg.componentSrcMap shape.
const sorted = Object.fromEntries(Object.keys(map).sort().map((k) => [k, map[k].file]));
writeFileSync(resolve(import.meta.dirname, 'roster.json'), JSON.stringify(sorted, null, 2) + '\n');

// Explicit named re-exports, grouped by declaring file. `export *` across the
// barrels would silently drop names exported from two of them (Table), so the
// entry names every component exactly once.
const byFile = {};
for (const name of Object.keys(sorted)) {
  const { file, local } = map[name];
  (byFile[file] ??= []).push(local === name ? name : `${local} as ${name}`);
}
const entry = [
  '// GENERATED by .design-sync/gen-roster.mjs — do not edit by hand.',
  '// Bundle entry for the design-sync converter: the exact RFDS surface,',
  '// re-exported so every component lands on window.RFDS.',
  '',
  '// MUST stay first: ES modules evaluate imports in source order, so this',
  '// installs a browser-safe `process` before any component module reads',
  '// server env at module scope. See .design-sync/process-shim.ts.',
  'import "./process-shim";',
  '',
  ...Object.keys(byFile).sort().map(
    (f) => `export { ${byFile[f].sort().join(', ')} } from "../${f.replace(/\.tsx?$/, '')}";`,
  ),
  '',
].join('\n');
writeFileSync(resolve(import.meta.dirname, 'ds-entry.ts'), entry);

// Local declared name per component, for consumers that must find the
// declaration in its own file (gen-props.mjs). roster.json cannot carry this —
// its shape is cfg.componentSrcMap's ({Name: path}).
writeFileSync(
  resolve(import.meta.dirname, 'locals.json'),
  JSON.stringify(Object.fromEntries(Object.keys(sorted).map((k) => [k, map[k].local])), null, 2) + '\n',
);

console.error(`roster: ${Object.keys(sorted).length} components across ${Object.keys(byFile).length} files`);
console.error(`type-only skipped: ${skipped.length}; layers excluded: ${[...NOT_COMPONENTS].join(', ')}`);
